# Generated by Django 4.2.4 on 2023-09-04 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingHubApp', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='OTP_expire',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 7, 32, 6, 143493, tzinfo=datetime.timezone.utc)),
        ),
    ]
