# Generated by Django 4.2.4 on 2023-09-04 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingHubApp', '0003_passwordresetotp_otp_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='OTP_expire',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 12, 21, 39, 922688, tzinfo=datetime.timezone.utc)),
        ),
    ]
