# Generated by Django 4.2.4 on 2023-12-10 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingHubApp', '0004_alter_passwordresetotp_otp_expire'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='OTP_expire',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 14, 10, 31, 606800, tzinfo=datetime.timezone.utc)),
        ),
    ]
