# Generated by Django 5.0.2 on 2024-02-17 15:35

import BookingHubApp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingHubApp', '0007_alter_passwordresetotp_otp_expire'),
    ]

    operations = [
        migrations.CreateModel(
            name='filterdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Location', models.TextField(max_length=50)),
                ('Capacity_of_Guests', models.IntegerField()),
                ('Rate', models.CharField(max_length=50)),
                ('Address', models.TextField(max_length=200)),
                ('Contact', models.CharField(max_length=15)),
                ('Event_Space', models.IntegerField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to=BookingHubApp.models.filepath)),
            ],
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='OTP_expire',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 15, 40, 0, 368501, tzinfo=datetime.timezone.utc)),
        ),
    ]
