# Generated by Django 5.0.2 on 2024-02-17 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingHubApp', '0008_filterdata_alter_passwordresetotp_otp_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='OTP_expire',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 19, 53, 35, 149265, tzinfo=datetime.timezone.utc)),
        ),
    ]
