# Generated by Django 5.0.2 on 2024-02-24 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingHubApp', '0009_alter_passwordresetotp_otp_expire'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=15)),
                ('Email_address', models.CharField(max_length=50)),
                ('Event_date', models.CharField(max_length=30)),
                ('Event_time', models.CharField(max_length=30)),
                ('No_of_Guests', models.IntegerField()),
                ('Message', models.TextField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='OTP_expire',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 15, 59, 55, 877311, tzinfo=datetime.timezone.utc)),
        ),
    ]
