# Generated by Django 5.0.2 on 2024-02-24 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingHubApp', '0011_alter_passwordresetotp_otp_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='OTP_expire',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 16, 29, 19, 328890, tzinfo=datetime.timezone.utc)),
        ),
    ]
