# Generated by Django 4.1 on 2025-04-07 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingHubApp', '0012_alter_passwordresetotp_otp_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='OTP_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 9, 52, 42, 360856, tzinfo=datetime.timezone.utc)),
        ),
    ]
